// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ConfirmPublicSubscriberData, ConfirmPublicSubscriberErrors, ConfirmPublicSubscriberResponses, CreatePublicSubscriberData, CreatePublicSubscriberErrors, CreatePublicSubscriberResponses, GetPublicArticleBySlugData, GetPublicArticleBySlugErrors, GetPublicArticleBySlugResponses, GetPublicArticlesData, GetPublicArticlesResponses, GetPublicCategoriesData, GetPublicCategoriesResponses, GetPublicEntitiesData, GetPublicEntitiesResponses, GetPublicEntityBySlugData, GetPublicEntityBySlugErrors, GetPublicEntityBySlugResponses, GetPublicSiteData, GetPublicSiteResponses, GetSubscriberListsData, GetSubscriberListsErrors, GetSubscriberListsResponses, ResolvePublicPermalinkData, ResolvePublicPermalinkErrors, ResolvePublicPermalinkResponses, UnsubscribeFromSpecificListsData, UnsubscribeFromSpecificListsErrors, UnsubscribeFromSpecificListsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create a new email subscriber
 */
export const createPublicSubscriber = <ThrowOnError extends boolean = false>(options: Options<CreatePublicSubscriberData, ThrowOnError>) => (options.client ?? client).post<CreatePublicSubscriberResponses, CreatePublicSubscriberErrors, ThrowOnError>({
    url: '/public/sites/{siteId}/subscribers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a public site by its ID. Includes menus and categories.
 */
export const getPublicSite = <ThrowOnError extends boolean = false>(options: Options<GetPublicSiteData, ThrowOnError>) => (options.client ?? client).get<GetPublicSiteResponses, unknown, ThrowOnError>({ url: '/public/sites/{siteId}', ...options });

/**
 * View all lists a subscriber is subscribed to and available public lists on the site. Requires unsubscribe token for authentication.
 */
export const getSubscriberLists = <ThrowOnError extends boolean = false>(options: Options<GetSubscriberListsData, ThrowOnError>) => (options.client ?? client).get<GetSubscriberListsResponses, GetSubscriberListsErrors, ThrowOnError>({ url: '/public/sites/{siteId}/subscribers/lists', ...options });

/**
 * Confirm email subscription using email address and 6-digit code sent in confirmation email
 */
export const confirmPublicSubscriber = <ThrowOnError extends boolean = false>(options: Options<ConfirmPublicSubscriberData, ThrowOnError>) => (options.client ?? client).post<ConfirmPublicSubscriberResponses, ConfirmPublicSubscriberErrors, ThrowOnError>({
    url: '/public/sites/{siteId}/subscribers/confirm',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Unsubscribe from one or more specific lists using the unsubscribe token. Auto-marks subscriber as unsubscribed if no active subscriptions remain.
 */
export const unsubscribeFromSpecificLists = <ThrowOnError extends boolean = false>(options: Options<UnsubscribeFromSpecificListsData, ThrowOnError>) => (options.client ?? client).post<UnsubscribeFromSpecificListsResponses, UnsubscribeFromSpecificListsErrors, ThrowOnError>({
    url: '/public/sites/{siteId}/subscribers/unsubscribe',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get public entities for a site. By default, only returns entities with permalinks on this site. Set hasPermalink=false to return all published entities in the organization.
 */
export const getPublicEntities = <ThrowOnError extends boolean = false>(options: Options<GetPublicEntitiesData, ThrowOnError>) => (options.client ?? client).get<GetPublicEntitiesResponses, unknown, ThrowOnError>({ url: '/public/sites/{siteId}/entities', ...options });

/**
 * Get public articles for a site. By default, only returns articles with permalinks on this site. Set hasPermalink=false to return all published articles in the organization.
 */
export const getPublicArticles = <ThrowOnError extends boolean = false>(options: Options<GetPublicArticlesData, ThrowOnError>) => (options.client ?? client).get<GetPublicArticlesResponses, unknown, ThrowOnError>({ url: '/public/sites/{siteId}/articles', ...options });

/**
 * Get all categories for a site with pagination support
 */
export const getPublicCategories = <ThrowOnError extends boolean = false>(options: Options<GetPublicCategoriesData, ThrowOnError>) => (options.client ?? client).get<GetPublicCategoriesResponses, unknown, ThrowOnError>({ url: '/public/sites/{siteId}/categories', ...options });

/**
 * Get a public entity by its slug
 */
export const getPublicEntityBySlug = <ThrowOnError extends boolean = false>(options: Options<GetPublicEntityBySlugData, ThrowOnError>) => (options.client ?? client).get<GetPublicEntityBySlugResponses, GetPublicEntityBySlugErrors, ThrowOnError>({ url: '/public/sites/{siteId}/entities/slug/{slug}', ...options });

/**
 * Get a public article by its slug
 */
export const getPublicArticleBySlug = <ThrowOnError extends boolean = false>(options: Options<GetPublicArticleBySlugData, ThrowOnError>) => (options.client ?? client).get<GetPublicArticleBySlugResponses, GetPublicArticleBySlugErrors, ThrowOnError>({ url: '/public/sites/{siteId}/articles/slug/{slug}', ...options });

/**
 * Resolve a permalink path to its resource (article, page, entity, category, or collection) for a specific site. Requires a public API key scoped to a site.
 */
export const resolvePublicPermalink = <ThrowOnError extends boolean = false>(options: Options<ResolvePublicPermalinkData, ThrowOnError>) => (options.client ?? client).get<ResolvePublicPermalinkResponses, ResolvePublicPermalinkErrors, ThrowOnError>({ url: '/public/sites/{siteId}/permalinks/path', ...options });
