// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://minima.ltd/api/v1' | (string & {});
};

/**
 * Public Site
 */
export type PublicSite = {
    id: string;
    name: string;
    domain: string;
    categories?: Array<PublicSiteCategory>;
    externalLinks: ExternalLinks;
    menus?: Array<PublicMenu>;
};

/**
 * Public Site Category
 */
export type PublicSiteCategory = {
    name: string;
    slug: string;
    path: string;
};

/**
 * External Links
 */
export type ExternalLinks = {
    amazon?: string;
    appleAppStore?: string;
    appleArcade?: string;
    appleNews?: string;
    applePodcasts?: string;
    bandcamp?: string;
    beatport?: string;
    bluesky?: string;
    chromeWebStore?: string;
    epicGamesStore?: string;
    facebook?: string;
    github?: string;
    googlePlay?: string;
    instagram?: string;
    soundCloud?: string;
    steam?: string;
    telegram?: string;
    tiktok?: string;
    wikipedia?: string;
    x?: string;
    youtube?: string;
};

/**
 * Menu
 */
export type PublicMenu = {
    id: string;
    name: string;
    slug: string;
    location: string | null;
    description: string | null;
    status: 'published';
    items?: Array<PublicMenuItem>;
};

/**
 * Menu Item
 */
export type PublicMenuItem = {
    id: string;
    label: string;
    linkType: 'path';
    path: string;
    position: number;
    openInNewTab: boolean;
} | {
    id: string;
    label: string;
    linkType: 'permalink';
    path: string;
    position: number;
    openInNewTab: boolean;
} | {
    id: string;
    label: string;
    linkType: 'external';
    url: string;
    position: number;
    openInNewTab: boolean;
};

/**
 * Tiptap Document
 */
export type TiptapSchema = DocumentNode;

/**
 * Document Node
 */
export type DocumentNode = {
    type: 'doc';
    attrs?: {
        [key: string]: unknown;
    };
    content?: Array<TiptapNode>;
};

/**
 * Tiptap Node
 */
export type TiptapNode = ({
    type: 'doc';
} & DocumentNode) | ({
    type: 'paragraph';
} & ParagraphNode) | ({
    type: 'heading';
} & HeadingNode) | ({
    type: 'bulletList';
} & BulletListNode) | ({
    type: 'orderedList';
} & OrderedListNode) | ({
    type: 'listItem';
} & ListItemNode) | ({
    type: 'blockquote';
} & BlockquoteNode) | ({
    type: 'codeBlock';
} & CodeBlockNode) | ({
    type: 'imageNode';
} & ImageNode) | ({
    type: 'youtube';
} & YouTubeNode) | ({
    type: 'pullQuote';
} & PullQuoteNode) | ({
    type: 'entityEmbed';
} & EntityEmbedNode) | ({
    type: 'text';
} & TextNode);

/**
 * Paragraph Node
 */
export type ParagraphNode = {
    type: 'paragraph';
    attrs?: {
        [key: string]: unknown;
    };
    content?: Array<TiptapNode>;
};

/**
 * Heading Node
 */
export type HeadingNode = {
    type: 'heading';
    attrs?: {
        level: number;
        [key: string]: unknown | number;
    };
    content?: Array<TiptapNode>;
};

/**
 * Bullet List Node
 */
export type BulletListNode = {
    type: 'bulletList';
    attrs?: {
        [key: string]: unknown;
    };
    content?: Array<TiptapNode>;
};

/**
 * Ordered List Node
 */
export type OrderedListNode = {
    type: 'orderedList';
    attrs?: {
        start?: number;
        [key: string]: unknown | number | undefined;
    };
    content?: Array<TiptapNode>;
};

/**
 * List Item Node
 */
export type ListItemNode = {
    type: 'listItem';
    attrs?: {
        [key: string]: unknown;
    };
    content?: Array<TiptapNode>;
};

/**
 * Blockquote Node
 */
export type BlockquoteNode = {
    type: 'blockquote';
    attrs?: {
        [key: string]: unknown;
    };
    content?: Array<TiptapNode>;
};

/**
 * Code Block Node
 */
export type CodeBlockNode = {
    type: 'codeBlock';
    attrs?: {
        language?: string;
        [key: string]: unknown | string | undefined;
    };
    content?: Array<TextNode>;
};

/**
 * Text Node
 */
export type TextNode = {
    type: 'text';
    text: string;
    marks?: Array<{
        type: 'bold';
        attrs?: {
            [key: string]: unknown;
        };
    } | {
        type: 'italic';
        attrs?: {
            [key: string]: unknown;
        };
    } | {
        type: 'strike';
        attrs?: {
            [key: string]: unknown;
        };
    } | {
        type: 'code';
        attrs?: {
            [key: string]: unknown;
        };
    } | {
        type: 'link';
        attrs: {
            href: string;
            target?: string;
            rel?: string;
            class?: string;
        };
    } | {
        type: string;
        attrs?: {
            [key: string]: unknown;
        };
    }>;
};

/**
 * Image Node
 */
export type ImageNode = {
    type: 'imageNode';
    attrs?: {
        src: string;
        alt?: string;
        title?: string;
        width?: number;
        height?: number;
        [key: string]: unknown | string | number | undefined;
    };
};

/**
 * YouTube Node
 */
export type YouTubeNode = {
    type: 'youtube';
    attrs?: {
        src: string;
        [key: string]: unknown | string;
    };
};

/**
 * Pull Quote Node
 */
export type PullQuoteNode = {
    type: 'pullQuote';
    attrs?: {
        text: string;
        attribution?: string;
        [key: string]: unknown | string | undefined;
    };
};

/**
 * Entity Embed Node - embeds an entity inline within the document
 */
export type EntityEmbedNode = {
    type: 'entityEmbed';
    attrs?: {
        /**
         * The ID of the embedded entity
         */
        entityId: string;
        /**
         * The name of the embedded entity
         */
        entityName?: string;
        /**
         * The type of the embedded entity
         */
        entityType?: string;
        [key: string]: unknown | string | undefined;
    };
    content?: Array<TiptapNode>;
};

/**
 * Published Category
 */
export type PublicCategory = {
    id: string;
    name: string;
    slug: string;
    parent?: {
        id: string;
        name: string;
        slug: string;
    };
};

/**
 * Published Image
 */
export type PublicImage = {
    id: string;
    attributes?: {
        [key: string]: never;
    };
    caption?: string;
    credit?: string;
    contentType: string;
    path: string;
    height: number;
    width: number;
    tags: Array<PublicTag>;
};

/**
 * Tag
 */
export type PublicTag = {
    name: string;
    slug: string;
};

/**
 * Meta information for paginated responses
 */
export type PublicPaginationMeta = {
    total: number;
    limit: number;
    offset: number;
    page: number;
    totalPages: number;
};

/**
 * Published Article
 */
export type PublicArticle = {
    id: string;
    attributes?: PublicArticleAttributes;
    author: PublicUser;
    body: TiptapSchema;
    categories: Array<PublicSiteCategory>;
    description?: string;
    /**
     * Resolved entity graph
     */
    graph?: Graph;
    headline: string;
    heroImage?: PublicImage;
    images: Array<PublicImage>;
    permalink: {
        path: string;
    };
    publishedAt: number;
    relationships: PublicArticleRelationships;
    schema: {
        [key: string]: unknown;
    };
    slug: string;
    subHeadline?: string;
    tags: Array<PublicTag>;
    type: 'Article' | 'NewsArticle';
};

/**
 * Article Attributes
 */
export type PublicArticleAttributes = {
    reviewScore?: {
        value: number;
        ratingSystem: {
            display: 'stars' | 'percentage' | 'numbers';
            precision: 'integer' | 'decimal';
            maxRating: number;
            minRating: number;
            step?: number;
        };
    };
};

/**
 * Public User
 */
export type PublicUser = {
    avatar?: PublicImage;
    id: string;
    name: string;
};

/**
 * Array of resolved entities with their relationships traversed to the requested depth
 */
export type Graph = Array<GraphEntity>;

/**
 * Resolved graph entity with nested relationships
 */
export type GraphEntity = {
    id: string;
    body?: TiptapSchema;
    categories?: Array<PublicCategory>;
    externalUrl?: string;
    heroImage?: PublicImage;
    images?: Array<PublicImage>;
    name: string;
    permalink: {
        path: string;
        site: {
            domain: string;
        };
    };
    publishedAt: number;
    slug: string;
    status: 'published';
    type: string;
    attributes?: {
        [key: string]: unknown;
    };
    /**
     * Related entities grouped by relationship type
     */
    relationships: {
        [key: string]: {
            type: string;
            label: string;
            entity: GraphEntity;
        } | Array<{
            type: string;
            label: string;
            entity: GraphEntity;
        }>;
    };
};

/**
 * Public Article Relationships
 */
export type PublicArticleRelationships = {
    itemReviewed?: Array<{
        entity: Array<{
            id: string;
            body?: TiptapSchema;
            categories?: Array<PublicCategory>;
            externalUrl?: string;
            heroImage?: PublicImage;
            images?: Array<PublicImage>;
            name: string;
            permalink: {
                path: string;
                site: {
                    domain: string;
                };
            };
            publishedAt: number;
            slug: string;
            status: 'published';
        }>;
    }>;
    about?: Array<{
        entity: Array<{
            id: string;
            body?: TiptapSchema;
            categories?: Array<PublicCategory>;
            externalUrl?: string;
            heroImage?: PublicImage;
            images?: Array<PublicImage>;
            name: string;
            permalink: {
                path: string;
                site: {
                    domain: string;
                };
            };
            publishedAt: number;
            slug: string;
            status: 'published';
        }>;
    }>;
    mentions?: Array<{
        entity: Array<{
            id: string;
            body?: TiptapSchema;
            categories?: Array<PublicCategory>;
            externalUrl?: string;
            heroImage?: PublicImage;
            images?: Array<PublicImage>;
            name: string;
            permalink: {
                path: string;
                site: {
                    domain: string;
                };
            };
            publishedAt: number;
            slug: string;
            status: 'published';
        }>;
    }>;
};

/**
 * Paginated Category List
 */
export type CategoryListResponse = {
    data: Array<{
        name: string;
        slug: string;
        path: string;
        permalink: {
            path: string;
        } | null;
    }>;
    pagination: PublicPaginationMeta;
};

/**
 * Published Page
 */
export type PublicPage = {
    id: string;
    body: TiptapSchema;
    headline: string;
    permalink: {
        path: string;
    };
    publishedAt: number;
    slug: string;
    type: 'AboutPage' | 'ContactPage' | 'WebPage';
    updatedAt: number;
};

/**
 * Permalink lookup response
 */
export type PermalinkLookupResponse = {
    resourceType: 'article' | 'page' | 'entity' | 'category' | 'collection';
    resourceId: string;
} | {
    resourceType: 'redirect';
    redirectTo: {
        path: string;
    };
};

/**
 * Permalink Resolve Response
 */
export type PermalinkResolveResponse = ArticleResponse | PageResponse | PublicEntityResponse | CategoryWithArticlesResponse | CollectionResponse | RedirectResponse;

/**
 * Article Response
 */
export type ArticleResponse = {
    article: PublicArticle;
    meta: {
        resourceType: 'article';
    };
};

/**
 * Page Response
 */
export type PageResponse = {
    page: PublicPage;
    meta: {
        resourceType: 'page';
    };
};

/**
 * Public Entity Response
 */
export type PublicEntityResponse = {
    entity: {
        id: string;
        body?: TiptapSchema;
        categories?: Array<PublicCategory>;
        externalUrl?: string;
        heroImage?: PublicImage;
        images?: Array<PublicImage>;
        name: string;
        permalink: {
            path: string;
            site: {
                domain: string;
            };
        };
        publishedAt: number;
        slug: string;
        status: 'published';
    };
    meta: {
        resourceType: 'entity';
    };
};

/**
 * Category with Articles
 */
export type CategoryWithArticlesResponse = {
    meta: {
        resourceType: 'category';
    };
    category: PublicSiteCategory;
    articles: Array<PublicArticle>;
    pagination: PublicPaginationMeta;
};

/**
 * Collection with Items
 */
export type CollectionResponse = {
    meta: {
        resourceType: 'collection';
    };
    id: string;
    name: string;
    slug: string;
    items: Array<CollectionItem>;
};

/**
 * Collection Item
 */
export type CollectionItem = {
    body: TiptapSchema | null;
    position: number;
    entity: {
        id: string;
        externalUrl: string | null;
        name: string;
        schema: {
            [key: string]: unknown;
        };
        slug: string;
        images: Array<PublicImage>;
        relationships: Array<{
            id: string;
            relationship: string;
            relatedEntity: {
                id: string;
                name: string;
                slug: string;
            };
        }>;
    } | null;
};

/**
 * Redirect Response
 */
export type RedirectResponse = {
    meta: {
        resourceType: 'redirect';
    };
    redirectTo: {
        path: string;
    };
};

/**
 * Preview Response - returns unpublished content
 */
export type PreviewResponse = PreviewArticleResponse | PreviewPageResponse | PreviewEntityResponse;

/**
 * Preview Article Response
 */
export type PreviewArticleResponse = {
    article: PublicArticle;
    meta: {
        resourceType: 'article';
        preview: true;
    };
};

/**
 * Preview Page Response
 */
export type PreviewPageResponse = {
    page: PublicPage;
    meta: {
        resourceType: 'page';
        preview: true;
    };
};

/**
 * Preview Entity Response
 */
export type PreviewEntityResponse = {
    entity: {
        id: string;
        body?: TiptapSchema;
        categories?: Array<PublicCategory>;
        externalUrl?: string;
        heroImage?: PublicImage;
        images?: Array<PublicImage>;
        name: string;
        permalink: {
            path: string;
            site: {
                domain: string;
            };
        };
        publishedAt: number;
        slug: string;
        status: 'published';
    };
    meta: {
        resourceType: 'entity';
        preview: true;
    };
};

export type CreatePublicSubscriberData = {
    body?: {
        email: string;
        firstName?: string;
        siteId: string;
        listId?: string;
        source?: string;
        metadata?: {
            [key: string]: unknown;
        };
        utm?: {
            [key: string]: string;
        };
        countryCode?: string;
    };
    path: {
        /**
         * Site ID
         */
        siteId: string;
    };
    query?: never;
    url: '/public/sites/{siteId}/subscribers';
};

export type CreatePublicSubscriberErrors = {
    /**
     * Site not found
     */
    404: unknown;
};

export type CreatePublicSubscriberResponses = {
    /**
     * Subscriber created or already exists
     */
    200: {
        data: {
            id: string;
            status: string;
        };
    };
};

export type CreatePublicSubscriberResponse = CreatePublicSubscriberResponses[keyof CreatePublicSubscriberResponses];

export type GetPublicSiteData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
    };
    query?: never;
    url: '/public/sites/{siteId}';
};

export type GetPublicSiteErrors = {
    /**
     * Site not found
     */
    404: unknown;
};

export type GetPublicSiteResponses = {
    /**
     * Site retrieved successfully
     */
    200: PublicSite;
};

export type GetPublicSiteResponse = GetPublicSiteResponses[keyof GetPublicSiteResponses];

export type GetSubscriberListsData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
    };
    query: {
        email: string;
        token: string;
    };
    url: '/public/sites/{siteId}/subscribers/lists';
};

export type GetSubscriberListsErrors = {
    /**
     * Invalid subscriber or token
     */
    404: unknown;
};

export type GetSubscriberListsResponses = {
    /**
     * Successfully retrieved subscriber lists
     */
    200: {
        data: {
            subscriptions: Array<{
                id: string;
                name: string;
                description: string | null;
                slug: string;
            }>;
            availableLists: Array<{
                id: string;
                name: string;
                description: string | null;
                slug: string;
            }>;
        };
    };
};

export type GetSubscriberListsResponse = GetSubscriberListsResponses[keyof GetSubscriberListsResponses];

export type ConfirmPublicSubscriberData = {
    body?: {
        email: string;
        code: string;
    };
    path: {
        /**
         * Site ID
         */
        siteId: string;
    };
    query?: never;
    url: '/public/sites/{siteId}/subscribers/confirm';
};

export type ConfirmPublicSubscriberErrors = {
    /**
     * Invalid confirmation link - subscriber not found or incorrect code
     */
    404: unknown;
};

export type ConfirmPublicSubscriberResponses = {
    /**
     * Successfully confirmed or already confirmed
     */
    200: {
        ok: boolean;
        message: string;
        alreadyConfirmed?: boolean;
    };
};

export type ConfirmPublicSubscriberResponse = ConfirmPublicSubscriberResponses[keyof ConfirmPublicSubscriberResponses];

export type UnsubscribeFromSpecificListsData = {
    body?: {
        email: string;
        token: string;
        listIds: Array<string>;
    };
    path: {
        /**
         * Site ID
         */
        siteId: string;
    };
    query?: never;
    url: '/public/sites/{siteId}/subscribers/unsubscribe';
};

export type UnsubscribeFromSpecificListsErrors = {
    /**
     * Invalid subscriber, token, or one or more lists not found
     */
    404: unknown;
};

export type UnsubscribeFromSpecificListsResponses = {
    /**
     * Successfully unsubscribed from specified lists
     */
    200: {
        data: {
            unsubscribedLists: Array<{
                id: string;
                name?: string;
                slug?: string;
            }>;
            hasActiveSubscriptions: boolean;
            message: string;
        };
    };
};

export type UnsubscribeFromSpecificListsResponse = UnsubscribeFromSpecificListsResponses[keyof UnsubscribeFromSpecificListsResponses];

export type GetPublicEntitiesData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
    };
    query?: {
        category?: string;
        /**
         * Case-insensitive search on entity name, including partial matches
         */
        query?: string;
        slug?: string;
        limit?: number;
        offset?: number;
        orderBy?: string;
        order?: string;
        type?: string;
        /**
         * Only return entities with permalinks on this site
         */
        hasPermalink?: string;
    };
    url: '/public/sites/{siteId}/entities';
};

export type GetPublicEntitiesResponses = {
    /**
     * 200 OK
     */
    200: {
        data: Array<{
            id: string;
            body?: TiptapSchema;
            categories?: Array<PublicCategory>;
            externalUrl?: string;
            heroImage?: PublicImage;
            images?: Array<PublicImage>;
            name: string;
            permalink: {
                path: string;
                site: {
                    domain: string;
                };
            };
            publishedAt: number;
            slug: string;
            status: 'published';
        } & {
            permalink: {
                path: string;
                site: {
                    domain: string;
                };
            } | null;
        }>;
        pagination: PublicPaginationMeta;
    };
};

export type GetPublicEntitiesResponse = GetPublicEntitiesResponses[keyof GetPublicEntitiesResponses];

export type GetPublicArticlesData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
    };
    query?: {
        category?: string;
        slug?: string;
        limit?: number;
        offset?: number;
        orderBy?: string;
        order?: string;
        type?: 'Article' | 'NewsArticle';
        tag?: string;
    };
    url: '/public/sites/{siteId}/articles';
};

export type GetPublicArticlesResponses = {
    /**
     * 200 OK
     */
    200: {
        data: Array<PublicArticle>;
        pagination: PublicPaginationMeta;
    };
};

export type GetPublicArticlesResponse = GetPublicArticlesResponses[keyof GetPublicArticlesResponses];

export type GetPublicCategoriesData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
    };
    query?: {
        limit?: number;
        offset?: number;
        orderBy?: string;
        order?: string;
    };
    url: '/public/sites/{siteId}/categories';
};

export type GetPublicCategoriesResponses = {
    /**
     * 200 OK
     */
    200: CategoryListResponse;
};

export type GetPublicCategoriesResponse = GetPublicCategoriesResponses[keyof GetPublicCategoriesResponses];

export type GetPublicPageByIdData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
        /**
         * Page ID
         */
        id: string;
    };
    query?: never;
    url: '/public/sites/{siteId}/pages/{id}';
};

export type GetPublicPageByIdErrors = {
    /**
     * 404 Not Found - Page not found
     */
    404: unknown;
};

export type GetPublicPageByIdResponses = {
    /**
     * Public page retrieved successfully
     */
    200: PublicPage;
};

export type GetPublicPageByIdResponse = GetPublicPageByIdResponses[keyof GetPublicPageByIdResponses];

export type GetPublicPageBySlugData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
        slug: string;
    };
    query?: never;
    url: '/public/sites/{siteId}/pages/slug/{slug}';
};

export type GetPublicPageBySlugErrors = {
    /**
     * 404 Not Found - Page not found
     */
    404: unknown;
};

export type GetPublicPageBySlugResponses = {
    /**
     * Public page retrieved successfully
     */
    200: PublicPage;
};

export type GetPublicPageBySlugResponse = GetPublicPageBySlugResponses[keyof GetPublicPageBySlugResponses];

export type GetPermalinkByPathData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
    };
    query: {
        /**
         * The permalink path
         */
        path: string;
    };
    url: '/public/sites/{siteId}/permalinks';
};

export type GetPermalinkByPathErrors = {
    /**
     * 404 Not Found - Permalink not found
     */
    404: unknown;
};

export type GetPermalinkByPathResponses = {
    /**
     * Permalink found
     */
    200: PermalinkLookupResponse;
};

export type GetPermalinkByPathResponse = GetPermalinkByPathResponses[keyof GetPermalinkByPathResponses];

export type GetPublicEntityByIdData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
        /**
         * Entity ID
         */
        id: string;
    };
    query?: {
        /**
         * Set to "graph" to include resolved entity graph
         */
        include?: 'graph';
        /**
         * Graph traversal depth (default: 1, max: 3)
         */
        depth?: number;
    };
    url: '/public/sites/{siteId}/entities/{id}';
};

export type GetPublicEntityByIdErrors = {
    /**
     * 404 Not Found - Entity not found
     */
    404: unknown;
};

export type GetPublicEntityByIdResponses = {
    /**
     * Public entity retrieved successfully
     */
    200: {
        id: string;
        body?: TiptapSchema;
        categories?: Array<PublicCategory>;
        externalUrl?: string;
        heroImage?: PublicImage;
        images?: Array<PublicImage>;
        name: string;
        permalink: {
            path: string;
            site: {
                domain: string;
            };
        };
        publishedAt: number;
        slug: string;
        status: 'published';
    };
};

export type GetPublicEntityByIdResponse = GetPublicEntityByIdResponses[keyof GetPublicEntityByIdResponses];

export type GetPublicEntityBySlugData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
        slug: string;
    };
    query?: {
        /**
         * Set to "graph" to include resolved entity graph
         */
        include?: 'graph';
        /**
         * Graph traversal depth (default: 1, max: 3)
         */
        depth?: number;
    };
    url: '/public/sites/{siteId}/entities/slug/{slug}';
};

export type GetPublicEntityBySlugErrors = {
    /**
     * 403 Forbidden - Public API key required
     */
    403: unknown;
    /**
     * 404 Not Found - Public entity not found
     */
    404: unknown;
};

export type GetPublicEntityBySlugResponses = {
    /**
     * Public entity retrieved successfully
     */
    200: {
        id: string;
        body?: TiptapSchema;
        categories?: Array<PublicCategory>;
        externalUrl?: string;
        heroImage?: PublicImage;
        images?: Array<PublicImage>;
        name: string;
        permalink: {
            path: string;
            site: {
                domain: string;
            };
        };
        publishedAt: number;
        slug: string;
        status: 'published';
    };
};

export type GetPublicEntityBySlugResponse = GetPublicEntityBySlugResponses[keyof GetPublicEntityBySlugResponses];

export type GetPublicArticleByIdData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
        /**
         * Article ID
         */
        id: string;
    };
    query?: {
        /**
         * Set to "graph" to include resolved entity graph
         */
        include?: 'graph';
        /**
         * Graph traversal depth (default: 1, max: 3)
         */
        depth?: number;
    };
    url: '/public/sites/{siteId}/articles/{id}';
};

export type GetPublicArticleByIdErrors = {
    /**
     * 404 Not Found - Article not found
     */
    404: unknown;
};

export type GetPublicArticleByIdResponses = {
    /**
     * Public article retrieved successfully
     */
    200: PublicArticle;
};

export type GetPublicArticleByIdResponse = GetPublicArticleByIdResponses[keyof GetPublicArticleByIdResponses];

export type GetPublicArticleBySlugData = {
    body?: never;
    path: {
        /**
         * Site ID
         */
        siteId: string;
        slug: string;
    };
    query?: {
        /**
         * Set to "graph" to include resolved entity graph
         */
        include?: 'graph';
        /**
         * Graph traversal depth (default: 1, max: 3)
         */
        depth?: number;
    };
    url: '/public/sites/{siteId}/articles/slug/{slug}';
};

export type GetPublicArticleBySlugErrors = {
    /**
     * 403 Forbidden - Public API key required
     */
    403: unknown;
    /**
     * 404 Not Found - Public article not found
     */
    404: unknown;
};

export type GetPublicArticleBySlugResponses = {
    /**
     * Public article retrieved successfully
     */
    200: PublicArticle;
};

export type GetPublicArticleBySlugResponse = GetPublicArticleBySlugResponses[keyof GetPublicArticleBySlugResponses];

export type ResolvePublicPermalinkData = {
    body?: never;
    path: {
        /**
         * The site ID
         */
        siteId: string;
    };
    query: {
        /**
         * The permalink path to resolve
         */
        path: string;
        /**
         * Set to "graph" to include resolved entity graph
         */
        include?: 'graph';
        /**
         * Graph traversal depth (default: 1, max: 3)
         */
        depth?: number;
    };
    url: '/public/sites/{siteId}/permalinks/path';
};

export type ResolvePublicPermalinkErrors = {
    /**
     * 403 Forbidden - Public API key required
     */
    403: unknown;
    /**
     * 404 Not Found - Permalink not found
     */
    404: unknown;
};

export type ResolvePublicPermalinkResponses = {
    /**
     * 200 OK - Resource found.
     */
    200: PermalinkResolveResponse;
};

export type ResolvePublicPermalinkResponse = ResolvePublicPermalinkResponses[keyof ResolvePublicPermalinkResponses];

export type PreviewResourceData = {
    body?: never;
    path: {
        /**
         * The site ID
         */
        siteId: string;
        /**
         * The preview token
         */
        token: string;
    };
    query?: {
        /**
         * Set to "graph" to include resolved entity graph
         */
        include?: 'graph';
        /**
         * Graph traversal depth (default: 1, max: 3)
         */
        depth?: number;
    };
    url: '/public/sites/{siteId}/preview/{token}';
};

export type PreviewResourceErrors = {
    /**
     * 403 Forbidden - Token does not match site
     */
    403: unknown;
    /**
     * 404 Not Found - Token or resource not found
     */
    404: unknown;
    /**
     * 410 Gone - Preview token has expired
     */
    410: unknown;
};

export type PreviewResourceResponses = {
    /**
     * 200 OK - Resource found.
     */
    200: PreviewResponse;
};

export type PreviewResourceResponse = PreviewResourceResponses[keyof PreviewResourceResponses];
